# Generated by Django 6.0.1 on 2026-01-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='tour',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('mid', 'Mid'), ('hard', 'Hard')], default='mid', max_length=10),
        ),
        migrations.AlterField(
            model_name='tour',
            name='max_people',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
