# Generated by Django 6.0.1 on 2026-01-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('service', 'In Service'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
    ]
