# Generated by Django 6.0.1 on 2026-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_motorcycle_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='motorcycle',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('touring', 'Touring'), ('adventure', 'Adventure'), ('cruiser', 'Cruiser'), ('naked', 'Naked'), ('scooter', 'Scooter')], default='sport', max_length=30),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycles/'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_cc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20),
        ),
    ]
